In [ ]:
# Assignment 2
# Topic Numpy

# Import the Libraries
import numpy as np
import pandas as pd

Question 1


Create a numpy array containing the numbers from 1 to 10, the reshape it to a 2*5 matrix.

In [ ]:
arr1 = np.arange(1,11)
print(arr1)

[ 1  2  3  4  5  6  7  8  9 10]


In [ ]:
matrix = arr1.reshape(2,5)
print(matrix)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


Question 2


Create a numpy array containing the numbers from 1 to 20, then extract the elements between the 5th and 15th index.

In [ ]:
arr2 = np.arange(1,21)
print(arr2)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [ ]:
# Extract elements from index 5 to 15 (inclusive)

extracted_elements = arr2[5:16]
print(extracted_elements)

[ 6  7  8  9 10 11 12 13 14 15 16]


Question 3


Compute the mean, median, and standard deviation.

In [ ]:
mean=np.mean(arr2)
print(mean)

10.5


In [ ]:
median=np.median(arr2)
print(median)

10.5


In [ ]:
std_dev=np.std(arr2)
print(std_dev)

5.766281297335398


Question 4

Create a 2D array x of shape (3,4) and a 1D array y of shape (4,) Subtract y from each row of x using broadcasting.

In [ ]:
x = np.array([[1, 2, 3, 4],
           [5, 6, 7, 8],
           [9, 10, 11, 12]])

y = np.array([1, 2, 3, 4])

result = x-y

In [ ]:
print(x)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
print(y)

[1 2 3 4]


In [ ]:
print(result)

[[0 0 0 0]
 [4 4 4 4]
 [8 8 8 8]]


 Question 5

Create a DataFrame with columns:name, age, gender (10 rows)

In [ ]:
data = {
    'name': ['Aleena', 'Boby', 'Chandra', 'Dania', 'Evana', 'Franco', 'Geethu', 'Hari', 'Ishani', 'Jithu'],
    'age': [25, 30, 22, 28, 35, 29, 24, 31, 27, 33],
    'gender': ['Female', 'Male', 'Female', 'Female', 'Female', 'Male', 'Female', 'Male', 'Female', 'Male']
}

df= pd.DataFrame(data)
print(df)

      name  age  gender
0   Aleena   25  Female
1     Boby   30    Male
2  Chandra   22  Female
3    Dania   28  Female
4    Evana   35  Female
5   Franco   29    Male
6   Geethu   24  Female
7     Hari   31    Male
8   Ishani   27  Female
9    Jithu   33    Male


 Q 5 (1)

 Add a new column called Occupation.

In [ ]:
df ["Occupation"] = [
    "Programmer",
    "Manager",
    "Analyst",
    "Programmer",
    "Manager",
    "Analyst",
    "Programmer",
    "Manager",
    "Analyst",
    "Programmer"
    ]

print(df)

      name  age  gender  Occupation
0   Aleena   25  Female  Programmer
1     Boby   30    Male     Manager
2  Chandra   22  Female     Analyst
3    Dania   28  Female  Programmer
4    Evana   35  Female     Manager
5   Franco   29    Male     Analyst
6   Geethu   24  Female  Programmer
7     Hari   31    Male     Manager
8   Ishani   27  Female     Analyst
9    Jithu   33    Male  Programmer


Q 5(2)

Select rows where age >= 30.

In [ ]:
age_filter = df[df["age"]>= 30]
print (age_filter)

    name  age  gender  Occupation
1   Boby   30    Male     Manager
4  Evana   35  Female     Manager
7   Hari   31    Male     Manager
9  Jithu   33    Male  Programmer


Q 5 (3)

Convert DataFrame to CSV and read it back

In [ ]:
df.to_csv("students.csv",index=False)

In [ ]:
new_df=pd.read_csv("students.csv")
print(new_df)

      name  age  gender  Occupation
0   Aleena   25  Female  Programmer
1     Boby   30    Male     Manager
2  Chandra   22  Female     Analyst
3    Dania   28  Female  Programmer
4    Evana   35  Female     Manager
5   Franco   29    Male     Analyst
6   Geethu   24  Female  Programmer
7     Hari   31    Male     Manager
8   Ishani   27  Female     Analyst
9    Jithu   33    Male  Programmer
